# Site settings
url: "https://principles.design"
title: "Design Principles"
description: "An Open Source collection of Design Principles and methods"
twitter: "@dsgnprinciples"
twitter:
  username: dsgnprinciples
logo: /favicon.png

# Custom variables
twitter-url: "https://twitter.com/dsgnprinciples"
contribute-url: "https://github.com/benbrignell/principles.design#contributing"
gitter-url: "https://gitter.im/design-principles"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']

collections:
    examples:
        output: true
        permalink: /examples/:name
    guide:
        output: true
        permalink: /guide/:name
    components:
        output: false

defaults:
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

plugins:
- jekyll-last-modified-at # doesn't work with collections
- jekyll-seo-tag
- jekyll-redirect-from

liquid:
    error_mode: lax # because of featured loop on homepage throwing minor validation error
